site_name: Macro Cards Quiz Games - Player Documentation
pages:
- Home: index.md
- User Guide:
    - Overview: mc-overview.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true

extra_css: ['font-awesome.css']

# Repository
repo_name: 'macropeople/mcdocs'
repo_url: 'https://github.com/macropeople/mcdocs'

theme:
  name: material
  logo: 'img/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  favicon: img/favicon.ico
  custom_dir: 'theme'
copyright: All rights reserved &copy;2018 Macro People Ltd.
